/*
 * File: composeUMatrix.c
 *
 * MATLAB Coder version            : 2.6
 * C/C++ source code generated on  : 16-May-2014 12:41:07
 */

/* Include files */
#include "rt_nonfinite.h"
#include "composeCPPPrediction.h"
#include "composeUMatrix.h"

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */

/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  double d0;
  double d1;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    d0 = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d0 == 1.0) {
        y = rtNaN;
      } else if (d0 > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }

  return y;
}

/*
 * COMPOSEUMATRIX
 *     U_SYM = COMPOSEUMATRIX(IN1,IN2,IN3)
 * Arguments    : const double in1[9]
 *                const double in2[6]
 *                const double in3[8]
 *                double U_sym[54]
 * Return Type  : void
 */
void composeUMatrix(const double in1[9], const double in2[6], const double in3[8],
                    double U_sym[54])
{
  double t2;
  double t3;
  double t4;
  double t8;
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double t15;
  double t18;
  double t19;
  double t20;
  double x[54];

  /*     This function was generated by the Symbolic Math Toolbox version 6.0. */
  /*     16-May-2014 12:41:06 */
  t2 = fabs(in2[0]);
  t3 = fabs(in2[1]);
  t4 = fabs(in2[2]);
  t8 = (t2 * t2 + t3 * t3) + t4 * t4;
  t10 = in3[5] * sqrt(t8) * 0.5;
  t11 = sin(t10);
  t12 = 1.0 / sqrt(t8);
  if (in2[0] < 0.0) {
    t13 = -1.0;
  } else if (in2[0] > 0.0) {
    t13 = 1.0;
  } else if (in2[0] == 0.0) {
    t13 = 0.0;
  } else {
    t13 = in2[0];
  }

  t14 = 1.0 / rt_powd_snf(t8, 1.5);
  t15 = cos(t10);
  t10 = 1.0 / t8;
  if (in2[1] < 0.0) {
    t8 = -1.0;
  } else if (in2[1] > 0.0) {
    t8 = 1.0;
  } else if (in2[1] == 0.0) {
    t8 = 0.0;
  } else {
    t8 = in2[1];
  }

  if (in2[2] < 0.0) {
    t18 = -1.0;
  } else if (in2[2] > 0.0) {
    t18 = 1.0;
  } else if (in2[2] == 0.0) {
    t18 = 0.0;
  } else {
    t18 = in2[2];
  }

  t19 = in1[4] * t11 * t12;
  t20 = in1[6] * t11 * t12;
  x[0] = 0.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 0.0;
  x[4] = ((((((-in1[5] * t11 * t12 - in3[5] * in1[4] * t2 * t11 * t12 * t13 *
               0.5) + in1[5] * t2 * t11 * t13 * t14 * in2[0]) + in1[6] * t2 *
             t11 * t13 * t14 * in2[1]) + in1[7] * t2 * t11 * t13 * t14 * in2[2])
           - in3[5] * in1[5] * t2 * t13 * t15 * t10 * in2[0] * 0.5) - in3[5] *
          in1[6] * t2 * t13 * t15 * t10 * in2[1] * 0.5) - in3[5] * in1[7] * t2 *
    t13 * t15 * t10 * in2[2] * 0.5;
  x[5] = ((((((t19 - in3[5] * in1[5] * t2 * t11 * t12 * t13 * 0.5) - in1[4] * t2
              * t11 * t13 * t14 * in2[0]) - in1[6] * t2 * t11 * t13 * t14 * in2
             [2]) + in1[7] * t2 * t11 * t13 * t14 * in2[1]) + in3[5] * in1[4] *
           t2 * t13 * t15 * t10 * in2[0] * 0.5) + in3[5] * in1[6] * t2 * t13 *
          t15 * t10 * in2[2] * 0.5) - in3[5] * in1[7] * t2 * t13 * t15 * t10 *
    in2[1] * 0.5;
  x[6] = ((((((in1[7] * t11 * t12 - in3[5] * in1[6] * t2 * t11 * t12 * t13 * 0.5)
              - in1[4] * t2 * t11 * t13 * t14 * in2[1]) + in1[5] * t2 * t11 *
             t13 * t14 * in2[2]) - in1[7] * t2 * t11 * t13 * t14 * in2[0]) +
           in3[5] * in1[4] * t2 * t13 * t15 * t10 * in2[1] * 0.5) - in3[5] *
          in1[5] * t2 * t13 * t15 * t10 * in2[2] * 0.5) + in3[5] * in1[7] * t2 *
    t13 * t15 * t10 * in2[0] * 0.5;
  x[7] = ((((((-t20 - in3[5] * in1[7] * t2 * t11 * t12 * t13 * 0.5) - in1[4] *
              t2 * t11 * t13 * t14 * in2[2]) - in1[5] * t2 * t11 * t13 * t14 *
             in2[1]) + in1[6] * t2 * t11 * t13 * t14 * in2[0]) + in3[5] * in1[4]
           * t2 * t13 * t15 * t10 * in2[2] * 0.5) + in3[5] * in1[5] * t2 * t13 *
          t15 * t10 * in2[1] * 0.5) - in3[5] * in1[6] * t2 * t13 * t15 * t10 *
    in2[0] * 0.5;
  x[8] = 0.0;
  x[9] = 0.0;
  x[10] = 0.0;
  x[11] = 0.0;
  x[12] = 0.0;
  x[13] = ((((((-in1[6] * t11 * t12 - in3[5] * in1[4] * t3 * t11 * t12 * t8 *
                0.5) + in1[5] * t3 * t11 * t14 * t8 * in2[0]) + in1[6] * t3 *
              t11 * t14 * t8 * in2[1]) + in1[7] * t3 * t11 * t14 * t8 * in2[2])
            - in3[5] * in1[5] * t3 * t15 * t10 * t8 * in2[0] * 0.5) - in3[5] *
           in1[6] * t3 * t15 * t10 * t8 * in2[1] * 0.5) - in3[5] * in1[7] * t3 *
    t15 * t10 * t8 * in2[2] * 0.5;
  x[14] = ((((((-in1[7] * t11 * t12 - in3[5] * in1[5] * t3 * t11 * t12 * t8 *
                0.5) - in1[4] * t3 * t11 * t14 * t8 * in2[0]) - in1[6] * t3 *
              t11 * t14 * t8 * in2[2]) + in1[7] * t3 * t11 * t14 * t8 * in2[1])
            + in3[5] * in1[4] * t3 * t15 * t10 * t8 * in2[0] * 0.5) + in3[5] *
           in1[6] * t3 * t15 * t10 * t8 * in2[2] * 0.5) - in3[5] * in1[7] * t3 *
    t15 * t10 * t8 * in2[1] * 0.5;
  x[15] = ((((((t19 - in3[5] * in1[6] * t3 * t11 * t12 * t8 * 0.5) - in1[4] * t3
               * t11 * t14 * t8 * in2[1]) + in1[5] * t3 * t11 * t14 * t8 * in2[2])
             - in1[7] * t3 * t11 * t14 * t8 * in2[0]) + in3[5] * in1[4] * t3 *
            t15 * t10 * t8 * in2[1] * 0.5) - in3[5] * in1[5] * t3 * t15 * t10 *
           t8 * in2[2] * 0.5) + in3[5] * in1[7] * t3 * t15 * t10 * t8 * in2[0] *
    0.5;
  x[16] = ((((((in1[5] * t11 * t12 - in3[5] * in1[7] * t3 * t11 * t12 * t8 * 0.5)
               - in1[4] * t3 * t11 * t14 * t8 * in2[2]) - in1[5] * t3 * t11 *
              t14 * t8 * in2[1]) + in1[6] * t3 * t11 * t14 * t8 * in2[0]) + in3
            [5] * in1[4] * t3 * t15 * t10 * t8 * in2[2] * 0.5) + in3[5] * in1[5]
           * t3 * t15 * t10 * t8 * in2[1] * 0.5) - in3[5] * in1[6] * t3 * t15 *
    t10 * t8 * in2[0] * 0.5;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = 0.0;
  x[21] = 0.0;
  x[22] = ((((((-in1[7] * t11 * t12 - in3[5] * in1[4] * t4 * t11 * t12 * t18 *
                0.5) + in1[5] * t4 * t11 * t14 * t18 * in2[0]) + in1[6] * t4 *
              t11 * t14 * t18 * in2[1]) + in1[7] * t4 * t11 * t14 * t18 * in2[2])
            - in3[5] * in1[5] * t4 * t15 * t10 * t18 * in2[0] * 0.5) - in3[5] *
           in1[6] * t4 * t15 * t10 * t18 * in2[1] * 0.5) - in3[5] * in1[7] * t4 *
    t15 * t10 * t18 * in2[2] * 0.5;
  x[23] = ((((((t20 - in3[5] * in1[5] * t4 * t11 * t12 * t18 * 0.5) - in1[4] *
               t4 * t11 * t14 * t18 * in2[0]) - in1[6] * t4 * t11 * t14 * t18 *
              in2[2]) + in1[7] * t4 * t11 * t14 * t18 * in2[1]) + in3[5] * in1[4]
            * t4 * t15 * t10 * t18 * in2[0] * 0.5) + in3[5] * in1[6] * t4 * t15 *
           t10 * t18 * in2[2] * 0.5) - in3[5] * in1[7] * t4 * t15 * t10 * t18 *
    in2[1] * 0.5;
  x[24] = ((((((-in1[5] * t11 * t12 - in3[5] * in1[6] * t4 * t11 * t12 * t18 *
                0.5) - in1[4] * t4 * t11 * t14 * t18 * in2[1]) + in1[5] * t4 *
              t11 * t14 * t18 * in2[2]) - in1[7] * t4 * t11 * t14 * t18 * in2[0])
            + in3[5] * in1[4] * t4 * t15 * t10 * t18 * in2[1] * 0.5) - in3[5] *
           in1[5] * t4 * t15 * t10 * t18 * in2[2] * 0.5) + in3[5] * in1[7] * t4 *
    t15 * t10 * t18 * in2[0] * 0.5;
  x[25] = ((((((t19 - in3[5] * in1[7] * t4 * t11 * t12 * t18 * 0.5) - in1[4] *
               t4 * t11 * t14 * t18 * in2[2]) - in1[5] * t4 * t11 * t14 * t18 *
              in2[1]) + in1[6] * t4 * t11 * t14 * t18 * in2[0]) + in3[5] * in1[4]
            * t4 * t15 * t10 * t18 * in2[2] * 0.5) + in3[5] * in1[5] * t4 * t15 *
           t10 * t18 * in2[1] * 0.5) - in3[5] * in1[6] * t4 * t15 * t10 * t18 *
    in2[0] * 0.5;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = 0.0;
  x[29] = 0.0;
  x[30] = 0.0;
  x[31] = 0.0;
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = 0.0;
  x[36] = 0.0;
  x[37] = 0.0;
  x[38] = 0.0;
  x[39] = 0.0;
  x[40] = 0.0;
  x[41] = 0.0;
  x[42] = 0.0;
  x[43] = 0.0;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = 0.0;
  x[48] = in3[5];
  x[49] = 0.0;
  x[50] = 0.0;
  x[51] = 0.0;
  x[52] = 0.0;
  x[53] = 0.0;
  memcpy(&U_sym[0], &x[0], 54U * sizeof(double));
}

/*
 * File trailer for composeUMatrix.c
 *
 * [EOF]
 */
